import { Link, useParams } from 'react-router-dom'

interface PolicyContent { title: string; intro: string; sections: Array<{ heading: string; content: string }> }

const policies: Record<string, PolicyContent> = {
  'van-chuyen': { title: 'Chính sách vận chuyển', intro: 'Thông tin chung về quá trình Daisy chuẩn bị và giao sản phẩm.', sections: [{ heading: 'Xác nhận và chuẩn bị', content: 'Đơn hàng được kiểm tra tồn kho và xác nhận trước khi đóng gói. Sản phẩm thủ công có thể cần thêm thời gian hoàn thiện.' }, { heading: 'Phí vận chuyển', content: 'Phí được backend tính theo phương thức đang hoạt động và hiển thị tại bước kiểm tra thanh toán trước khi đặt hàng.' }, { heading: 'Theo dõi đơn', content: 'Khi có mã vận đơn, thông tin sẽ được cập nhật trong chi tiết đơn hàng của khách.' }] },
  'doi-tra': { title: 'Chính sách đổi trả', intro: 'Daisy hỗ trợ đổi trả để bảo vệ trải nghiệm mua sắm của bạn.', sections: [{ heading: 'Thời hạn', content: 'Liên hệ Daisy trong vòng 7 ngày kể từ khi nhận hàng nếu sản phẩm lỗi, hư hỏng do vận chuyển hoặc không đúng đơn.' }, { heading: 'Điều kiện', content: 'Sản phẩm cần còn nguyên trạng, chưa qua sử dụng và đi kèm bao bì/phụ kiện nhận được.' }, { heading: 'Sản phẩm thủ công', content: 'Sai khác nhỏ do chế tác thủ công không được xem là lỗi nếu không ảnh hưởng công năng và thẩm mỹ tổng thể.' }] },
  'bao-mat': { title: 'Chính sách bảo mật', intro: 'Daisy tôn trọng và bảo vệ thông tin cá nhân của khách hàng.', sections: [{ heading: 'Dữ liệu thu thập', content: 'Tên, email, điện thoại, địa chỉ và thông tin đơn hàng được dùng để xác nhận, giao hàng và hỗ trợ khách.' }, { heading: 'Sử dụng dữ liệu', content: 'Daisy không bán dữ liệu cá nhân. Thông tin chỉ được chia sẻ với bên vận chuyển hoặc nhà cung cấp cần thiết để hoàn tất đơn.' }, { heading: 'Bảo vệ tài khoản', content: 'Không chia sẻ token đăng nhập hoặc mật khẩu. Hãy đăng xuất trên thiết bị dùng chung.' }] },
  'thanh-toan': { title: 'Chính sách thanh toán', intro: 'Daisy hỗ trợ COD và chuyển khoản ngân hàng.', sections: [{ heading: 'COD', content: 'Khách thanh toán cho đơn vị vận chuyển khi nhận hàng. Trạng thái ban đầu là chưa thanh toán.' }, { heading: 'Chuyển khoản', content: 'Thông tin tài khoản, nội dung chuyển khoản và QR nếu có được backend tạo sau khi đơn hàng thành công.' }, { heading: 'Xác minh', content: 'Đơn chuyển khoản được xác nhận sau khi Daisy đối chiếu giao dịch. Không chuyển tiền theo thông tin ngoài màn hình xác nhận đơn.' }] },
  'dieu-khoan': { title: 'Điều khoản sử dụng', intro: 'Các nguyên tắc chung khi sử dụng website Daisy Handmade Store.', sections: [{ heading: 'Thông tin sản phẩm', content: 'Daisy cố gắng thể hiện màu sắc và chi tiết chính xác; hiển thị có thể khác nhẹ tùy thiết bị và đặc tính thủ công.' }, { heading: 'Giá và tồn kho', content: 'Giá, ưu đãi, phí vận chuyển và tồn kho cuối cùng do backend xác nhận trước khi tạo đơn.' }, { heading: 'Sử dụng hợp lệ', content: 'Không lạm dụng website, thử mã trái phép, can thiệp API hoặc sử dụng nội dung thương hiệu khi chưa được đồng ý.' }] },
  'huong-dan-mua-hang': { title: 'Hướng dẫn mua hàng', intro: 'Các bước đơn giản để chọn và đặt trang sức tại Daisy.', sections: [{ heading: '1. Chọn sản phẩm', content: 'Tìm kiếm, lọc danh mục và xem kỹ hình ảnh, chất liệu, tồn kho trên trang chi tiết.' }, { heading: '2. Kiểm tra giỏ', content: 'Chọn số lượng phù hợp. Giá trong local cart là tạm tính và sẽ được backend kiểm tra lại.' }, { heading: '3. Thanh toán', content: 'Nhập thông tin nhận hàng, chọn vận chuyển, coupon nếu có và COD hoặc chuyển khoản.' }, { heading: '4. Xác nhận', content: 'Xem preview tổng tiền backend rồi tạo đơn. Chỉ khi tạo thành công giỏ hàng mới được xóa.' }] },
}

export function PolicyPage() {
  const { policySlug = '' } = useParams<{ policySlug: string }>()
  const policy = policies[policySlug]
  if (!policy) return <div className="empty-state"><h1>Không tìm thấy nội dung</h1><Link to="/" className="button button-primary">Về trang chủ</Link></div>
  return <article className="content-page"><p className="eyebrow">Daisy Handmade Store</p><h1>{policy.title}</h1><p>{policy.intro}</p>{policy.sections.map((section) => <section key={section.heading} className="info-card"><h2>{section.heading}</h2><p>{section.content}</p></section>)}<p><small>Nội dung áp dụng cho website Daisy Handmade Store và có thể được cập nhật khi quy trình vận hành thay đổi.</small></p><Link to="/lien-he" className="section-link">Liên hệ Daisy nếu bạn cần hỗ trợ →</Link></article>
}
